---
title: "Lab4"
author: "Gulalai Shah"
date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
```

```{r}
report_03_11_2020 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State")
str(report_03_11_2020)
```
```{r}
view(report_03_11_2020)
```

```{r}
library(DT)
datatable(report_03_11_2020)
```

## Exercise Part 1

```{r}
report_03_13_2020 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State")
```
```{r}
str(report_03_13_2020)
```

```{r}
report_09_13_2020 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv"))
str(report_09_13_2020)
view(report_09_13_2020)
```

```{r}
report_09_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarize(total_counts = n())
```
```{r}
view(report_09_13_2020)
```
```{r}
report_09_13_2020 %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State) %>% 
  summarize(Confirmed = sum(Confirmed))
```
```{r}
report_09_13_2020 %>%
  group_by(Country_Region) %>% 
  summarize(Total_Deaths = sum(Deaths)) %>% 
  arrange(desc(Total_Deaths)) %>% 
  slice(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

```
## Exercise Part 2
```{r}
Top10Deaths <- report_03_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarize(Deaths = sum(Deaths)) %>% 
  arrange(desc(Deaths)) %>% 
  slice_max(Deaths, n= 10)
```
```{r}
ggplot(data = Top10Deaths, aes(x = Country_Region, y = Deaths)) + 
  geom_point()
```
```{r}
ggplot(data = Top10Deaths, aes(x = Country_Region, y = Deaths)) +
  geom_bar(stat = 'identity')
```
```{r}
Top10Confirmed <- report_03_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  arrange(desc(Confirmed)) %>% 
  slice_max(Confirmed, n= 10)
```
```{r}
ggplot(data = Top10Confirmed, aes(x = Country_Region, y = Confirmed)) +
  geom_point()
```
```{r}
ggplot(data = Top10Confirmed, aes(x = Country_Region, y = Confirmed)) +
  geom_bar(stat = 'identity')
```
```{r}
Top10Deaths <- report_09_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarize(Deaths = sum(Deaths)) %>% 
  arrange(desc(Deaths)) %>% 
  slice_max(Deaths, n= 10)
```
```{r}
ggplot(data = Top10Deaths, aes(x = Country_Region, y = Deaths)) +
  geom_point()
```
```{r}
ggplot(data = Top10Deaths, aes(x = Country_Region, y = Deaths)) +
  geom_bar(stat = 'identity')
```
```{r}
Top10Confirmed <- report_09_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  arrange(desc(Confirmed)) %>% 
  slice_max(Confirmed, n= 10)
```
```{r}
ggplot(data = Top10Confirmed, aes(x = Country_Region, y = Confirmed)) +
  geom_point()
```
```{r}
ggplot(data = Top10Confirmed, aes(x = Country_Region, y = Confirmed)) +
  geom_bar(stat = 'identity')
```
```{r}

```








