---
title: "Lab5"
author: "Gulalai Shah"
date: "9/21/2020"
output: html_document
---
```{r}
library(tidyverse)
```
```{r}
Confirmed_State_3_13 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>% 
  rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed))
```
```{r}
str(Confirmed_State_3_13)
```
```{r}
Confirmed_State_9_13 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed))
```
```{r}
str(Confirmed_State_9_13)
```
```{r}
setdiff(Confirmed_State_9_13$Province_State, Confirmed_State_3_13$Province_State)
```
```{r}
Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State != "Recovered")
```

```{r}
Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
      Confirmed_State_9_13, by = c("Province_State"))
```

```{r}
head(Confirmed_State_3_13_9_13_joined)
```
```{r}
tail(Confirmed_State_3_13_9_13_joined, 5)
```
```{r}
which(is.na(Confirmed_State_3_13_9_13_joined))
```
```{r}
Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
  rename(Confirmed_3_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
  select(-Country_Region.x, -Country_Region.y) %>% 
  replace_na(list(Confirmed_3_13_2020 = 0))
head(Confirmed_State_3_13_9_13_joined)
```
```{r}
which(is.na(Confirmed_State_3_13_9_13_joined))
```


```{r}
Confirmed_State_3_13_9_13_joined_long <- Confirmed_State_3_13_9_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")
```

```{r}
ggplot(Confirmed_State_3_13_9_13_joined_long, aes(x = Confirmed, y = Province_State)) +
  geom_point(aes(color = Date))
```
```{r}
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>% 
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```
```{r}
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv",
              destfile = "time_series_covid19_confirmed_global.csv")
```
```{r}
time_series_confirmed <- read_csv("time_series_covid19_confirmed_global.csv") %>% 
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```
```{r}
head(time_series_confirmed)
```
```{r}
time_series_confirmed_long <- time_series_confirmed %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Confirmed")
```

```{r}
head(time_series_confirmed_long)
```
```{r}
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv",
              destfile = "time_series_covid19_deaths_global.csv")
```
```{r}
time_series_deaths <- read_csv("time_series_covid19_deaths_global.csv") %>% 
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```
```{r}
time_series_deaths_long <- time_series_deaths %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "date", values_to = "Deaths")

head(time_series_deaths_long)
```
```{r}
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
```
```{r}
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, date, sep = ".") %>% 
  select(Key, Deaths)
```

```{r}

time_series_long_joined <- full_join(time_series_confirmed_long,
                                     time_series_deaths_long, by = c("Key")) %>% 
  select(-Key)
head(time_series_long_joined)
```
```{r}
which(is.na(time_series_long_joined$Confirmed))
```

```{r}
which(is.na(time_series_long_joined$Deaths))
```

```{r}
library(lubridate)
```
```{r}
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
```

```{r}
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```

```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
  ggplot(aes(x = Date, y = Deaths)) +
  geom_point() +
  geom_line() +
  ggtitle("US COVID-19 Deaths")
```
```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China", "Japan", "Korea, South", "Italy", "Spain", "US")) %>% 
    ggplot(aes(x = Date, y =  Deaths)) +
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")
```
```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China", "France", "Italy", "Korea, South", "US")) %>%
  ggplot(aes(x = Date, y = Deaths, color = Country_Region)) +
  geom_point() +
  geom_line() +
  ggtitle("COVID-19 Deaths")
```
```{r}
time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date, y = log2(Counts), fill = Report_Type, color = Report_Type)) +
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Cases")
```
## Exercises

## 1
# See my GitHub page under Lab4A

## 2


```{r}
Confirmed_06_13 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>%
  summarise(Confirmed = sum(Confirmed))
```
```{r}
str(Confirmed_06_13)
```
```{r}
Confirmed_09_13 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>%
  summarise(Confirmed = sum(Confirmed))
```


```{r}
str(Confirmed_09_13)
```

```{r}
Confirmed_06_13_09_13_joined <- full_join(Confirmed_06_13,
      Confirmed_09_13, by = c("Province_State"))
```

```{r}

Confirmed_06_13_09_13_joined <- full_join(Confirmed_06_13,
      Confirmed_09_13, by = c("Province_State")) %>% 
  rename(Confirmed_06_13 = "Confirmed.x", Confirmed_09_13 = "Confirmed.y") %>% 
  select(-Country_Region.x, -Country_Region.y) %>% 
  replace_na(list(Confirmed_06_13 = 0))
```


```{r}
which(is.na(Confirmed_06_13_09_13_joined))
```

```{r}
Confirmed_06_13_09_13_joined_long <- Confirmed_06_13_09_13_joined %>% 
  pivot_longer(-c(Province_State),
               names_to = "Date", values_to = "Confirmed")
```

```{r, fig.width = 5, fig.height= 7}

ggplot(Confirmed_06_13_09_13_joined_long, aes(x = Confirmed, y = Province_State)) +
  geom_col()
```

# 3

```{r, fig.width = 5, fig.height= 7}
ggplot(Confirmed_06_13_09_13_joined_long, aes(x = Confirmed, y = Province_State)) +
  geom_col() +
  ggtitle("Confirmed COVID-19 Cases per Province/State")
```

# 4

```{r}
time_series_long_joined %>% 
  group_by(Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  ggplot(aes(x = Date, y = Deaths)) +
  geom_point() +
  geom_line() +
  ggtitle("COVID-19 Deaths Worldwide")
```

# 5

```{r}
time_series_long_joined %>% 
  mutate(rate = Deaths/Confirmed, percent = rate * 100)
```
```{r}
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date, Deaths/Confirmed),
               names_to = "Report_Type", values_to = "Counts")
str(time_series_long_joined_counts)
```

# 6

```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths/Confirmed Cases Per Day")
```

# 7

```{r, fig.width = 5, fig.height= 5}
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("US","Brazil","India","Italy", 
                                "Mexico","Spain","France","Iran","Peru","UK")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("Top 10 Countries W/ COVID-19 Deaths")
```




# 8

```{r, fig.width = 5, fig.height= 5}
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("Brazil","United Kingdom","Italy", 
                                "Mexico", "US","Spain","France","Russia","Germany","China")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
  facet_wrap(~Country_Region, ncol=2, scales="free_y") +
    ggtitle("COVID-19 Deaths")
```






# 9

```{r}
time_series_confirmed_US_long <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")) %>% 
select(-c("UID","iso2","iso3","code3","FIPS","Admin2")) %>% 
  pivot_longer(-c("Province_State","Country_Region","Lat","Long_","Combined_Key"), names_to = "Dates", values_to = "Confirmed") %>% 
  filter(Province_State != "Recovered" )
```

```{r}
time_series_confirmed_US_long$Dates <- mdy(time_series_confirmed_US_long$Dates)
```

```{r, fig.width = 15, fig.height= 15}
i <- time_series_confirmed_US_long %>%
group_by(Province_State, Dates) %>%
summarise(SumConfirmed = sum(Confirmed)) %>% 
ggplot(aes(x = Dates,  y = SumConfirmed,  color = Province_State)) + 
geom_point() + 
geom_line() + 
facet_wrap(~Province_State, ncol = 5, scales = "free_y")
i
```



# 10 
```{r, fig.width = 7, fig.height= 7}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("US","Brazil","India","Italy", 
                                "Mexico","Spain","France","Iran","Peru","UK")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("Global COVID-19 Deaths") + 
    facet_wrap(~Country_Region, ncol=2, scales="free_y") + theme_dark() + theme(axis.text.x = element_text(colour = "Red", size = 12, angle = 90, hjust = 0.5, vjust = 0.5),
                        axis.text.y = element_text(colour = "Red", size = 12),
                        strip.text = element_text(face = "italic",  colour = "Red"),
                        text = element_text(size = 16)) + theme( panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "Red"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "Red")) 

```











